# compat shim — moved to utils/routing/ollama_manager.py
import os  # noqa: F401
import shutil  # noqa: F401
from utils.routing.ollama_manager import *  # noqa: F401,F403
from utils.routing.ollama_manager import (  # noqa: F401
    ROLES,
    ComputeValidationError,
    ComputeConflictError,
    ComputeDependencyError,
    InstanceTemplate,
    # private symbols used by tests
    _LABEL_MANAGER,
    _LABEL_INSTANCE,
    _HEALTH_TTL_SECONDS,
    _GPU_NAME_TTL_SECONDS,
    _health_cache_lock,
    _health_cache,
    _gpu_name_cache_lock,
    _gpu_name_cache,
    _host_gpu_name_cache_lock,
    _host_gpu_name_cache,
    _docker_client,
    _docker_exceptions,
    _dedupe_keep_order,
    _parse_gpu_device_ids,
    _detect_nvidia_runtime,
    _detect_amd_runtime,
    _resolve_gpu_backend,
    _detect_network,
    _build_templates,
    _check_endpoint_health,
    _exec_in_container,
    _parse_nvidia_name,
    _parse_amd_name,
    _parse_nvidia_proc_info,
    _detect_gpu_name,
    _get_gpu_name_cached,
    _detect_host_nvidia_name,
    _detect_host_amd_name,
    _detect_host_gpu_name,
    _get_host_gpu_name_cached,
    _is_managed_instance_container,
    _ensure_models_volume,
    _run_kwargs_for_template,
    _template_for_id,
    _describe_instance,
    _default_layer_routing,
    _parse_layer_routing,
    _choose_auto_target,
)
